
package sd.clt.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAP", targetNamespace = "http://srv.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSOAP {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAlbums", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListAlbums")
    @ResponseWrapper(localName = "listAlbumsResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListAlbumsResponse")
    @Action(input = "http://srv.sd/ServerSOAP/listAlbumsRequest", output = "http://srv.sd/ServerSOAP/listAlbumsResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://srv.sd/ServerSOAP/listAlbums/Fault/FileNotFoundException")
    })
    public List<String> listAlbums()
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPictures", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListPictures")
    @ResponseWrapper(localName = "listPicturesResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListPicturesResponse")
    @Action(input = "http://srv.sd/ServerSOAP/listPicturesRequest", output = "http://srv.sd/ServerSOAP/listPicturesResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://srv.sd/ServerSOAP/listPictures/Fault/FileNotFoundException")
    })
    public List<String> listPictures(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception
    ;

}
