
package sd.clt.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAP", targetNamespace = "http://srv.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSOAP {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAlbums", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListAlbums")
    @ResponseWrapper(localName = "listAlbumsResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListAlbumsResponse")
    @Action(input = "http://srv.sd/ServerSOAP/listAlbumsRequest", output = "http://srv.sd/ServerSOAP/listAlbumsResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://srv.sd/ServerSOAP/listAlbums/Fault/FileNotFoundException")
    })
    public List<String> listAlbums()
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPictures", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListPictures")
    @ResponseWrapper(localName = "listPicturesResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.ListPicturesResponse")
    @Action(input = "http://srv.sd/ServerSOAP/listPicturesRequest", output = "http://srv.sd/ServerSOAP/listPicturesResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://srv.sd/ServerSOAP/listPictures/Fault/FileNotFoundException")
    })
    public List<String> listPictures(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureData", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.GetPictureData")
    @ResponseWrapper(localName = "getPictureDataResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.GetPictureDataResponse")
    @Action(input = "http://srv.sd/ServerSOAP/getPictureDataRequest", output = "http://srv.sd/ServerSOAP/getPictureDataResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://srv.sd/ServerSOAP/getPictureData/Fault/IOException")
    })
    public byte[] getPictureData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAlbum", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.CreateAlbum")
    @ResponseWrapper(localName = "createAlbumResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.CreateAlbumResponse")
    @Action(input = "http://srv.sd/ServerSOAP/createAlbumRequest", output = "http://srv.sd/ServerSOAP/createAlbumResponse")
    public boolean createAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAlbum", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.DeleteAlbum")
    @ResponseWrapper(localName = "deleteAlbumResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.DeleteAlbumResponse")
    @Action(input = "http://srv.sd/ServerSOAP/deleteAlbumRequest", output = "http://srv.sd/ServerSOAP/deleteAlbumResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://srv.sd/ServerSOAP/deleteAlbum/Fault/IOException")
    })
    public void deleteAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadPicture", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.UploadPicture")
    @ResponseWrapper(localName = "uploadPictureResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.UploadPictureResponse")
    @Action(input = "http://srv.sd/ServerSOAP/uploadPictureRequest", output = "http://srv.sd/ServerSOAP/uploadPictureResponse")
    public boolean uploadPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePicture", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.DeletePicture")
    @ResponseWrapper(localName = "deletePictureResponse", targetNamespace = "http://srv.sd/", className = "sd.clt.ws.DeletePictureResponse")
    @Action(input = "http://srv.sd/ServerSOAP/deletePictureRequest", output = "http://srv.sd/ServerSOAP/deletePictureResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://srv.sd/ServerSOAP/deletePicture/Fault/IOException")
    })
    public void deletePicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws IOException_Exception
    ;

}
