
package sd.tp1.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAP", targetNamespace = "http://soap.srv.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListPictures", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetListPictures")
    @ResponseWrapper(localName = "getListPicturesResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetListPicturesResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/getListPicturesRequest", output = "http://soap.srv.sd/ServerSOAP/getListPicturesResponse")
    public List<String> getListPictures(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListAlbuns", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetListAlbuns")
    @ResponseWrapper(localName = "getListAlbunsResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetListAlbunsResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/getListAlbunsRequest", output = "http://soap.srv.sd/ServerSOAP/getListAlbunsResponse")
    public List<String> getListAlbuns();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureData", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetPictureData")
    @ResponseWrapper(localName = "getPictureDataResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.GetPictureDataResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/getPictureDataRequest", output = "http://soap.srv.sd/ServerSOAP/getPictureDataResponse")
    public byte[] getPictureData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAlbum", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.CreateAlbum")
    @ResponseWrapper(localName = "createAlbumResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.CreateAlbumResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/createAlbumRequest", output = "http://soap.srv.sd/ServerSOAP/createAlbumResponse")
    public boolean createAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAlbum", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.DeleteAlbum")
    @ResponseWrapper(localName = "deleteAlbumResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.DeleteAlbumResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/deleteAlbumRequest", output = "http://soap.srv.sd/ServerSOAP/deleteAlbumResponse")
    public void deleteAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePicture", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.DeletePicture")
    @ResponseWrapper(localName = "deletePictureResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.DeletePictureResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/deletePictureRequest", output = "http://soap.srv.sd/ServerSOAP/deletePictureResponse")
    public boolean deletePicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadPicture", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.UploadPicture")
    @ResponseWrapper(localName = "uploadPictureResponse", targetNamespace = "http://soap.srv.sd/", className = "sd.tp1.ws.UploadPictureResponse")
    @Action(input = "http://soap.srv.sd/ServerSOAP/uploadPictureRequest", output = "http://soap.srv.sd/ServerSOAP/uploadPictureResponse")
    public boolean uploadPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

}
